version: "3.7"

services:
  # app:
  #   image: pufferbommy/borrowing-things:latest
  #   container_name: borrowing-things
  #   environment:
  #     PGHOST: ${PGHOST}
  #     PGDATABASE: ${PGDATABASE}
  #     PGUSER: ${PGUSER}
  #     PGPASSWORD: ${PGPASSWORD}
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - my_network
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres_data:
