import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className="">
        <Header />
        <div className="h-screen flex pt-14">
          <main className="w-full overflow-auto p-4">{children}</main>
          <Toaster richColors theme="light" />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
